INSERT INTO CUSTOMERS (CUSTOMER_NAME, EMAIL, PHONE)
VALUES ('Ali Raza', 'ali.raza@gmail.com', '03001234567');

INSERT INTO PRODUCTS (PRODUCT_NAME, PRICE, STOCK)
VALUES ('Laptop', 100000, 10);

INSERT INTO ORDERS (CUSTOMER_ID, STATUS)
VALUES ((SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_NAME = 'Ali Raza'), 'Pending');

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY)
VALUES (
    (SELECT ORDER_ID FROM ORDERS WHERE CUSTOMER_ID = (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_NAME = 'Ali Raza')),
    (SELECT PRODUCT_ID FROM PRODUCTS WHERE PRODUCT_NAME = 'Laptop'),
    2
);

UPDATE PRODUCTS
SET STOCK = STOCK - 2
WHERE PRODUCT_NAME = 'Laptop';

UPDATE ORDERS
SET STATUS = 'Shipped'
WHERE CUSTOMER_ID = (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE CUSTOMER_NAME = 'Ali Raza');

SELECT DISTINCT c.CUSTOMER_NAME
FROM CUSTOMERS c
JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN PRODUCTS p ON p.PRODUCT_ID = oi.PRODUCT_ID
GROUP BY c.CUSTOMER_NAME
HAVING SUM(p.PRICE * oi.QUANTITY) > 50000;

SELECT p.PRODUCT_NAME, COUNT(*) AS TIMES_ORDERED
FROM ORDER_ITEMS oi
JOIN PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_NAME
ORDER BY TIMES_ORDERED DESC
FETCH FIRST 1 ROWS ONLY;

