SELECT e.FIRST_NAME, e.JOB_ID, d.DEPARTMENT_NAME, l.CITY
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID;

SELECT e.FIRST_NAME, e.SALARY, e.DEPARTMENT_ID
FROM EMPLOYEES e
WHERE e.SALARY > (
  SELECT AVG(SALARY) FROM EMPLOYEES e2 
  WHERE e2.DEPARTMENT_ID = e.DEPARTMENT_ID
);

SELECT e.EMPLOYEE_ID, e.FIRST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE e.DEPARTMENT_ID = (
  SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King'
)
AND e.FIRST_NAME <> 'Steven';

SELECT d.DEPARTMENT_NAME, e.FIRST_NAME, e.SALARY
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE (e.DEPARTMENT_ID, e.SALARY) IN (
  SELECT DEPARTMENT_ID, MAX(SALARY)
  FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID
);

SELECT l.CITY, COUNT(e.EMPLOYEE_ID) AS TOTAL_EMP
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
GROUP BY l.CITY
ORDER BY TOTAL_EMP DESC
FETCH FIRST 1 ROWS ONLY;

SELECT d.DEPARTMENT_NAME, m.FIRST_NAME AS MANAGER_NAME, COUNT(e.EMPLOYEE_ID) AS TOTAL_EMP
FROM DEPARTMENTS d
JOIN EMPLOYEES m ON d.MANAGER_ID = m.EMPLOYEE_ID
LEFT JOIN EMPLOYEES e ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME, m.FIRST_NAME;

SELECT e.FIRST_NAME, e.HIRE_DATE, m.FIRST_NAME AS MANAGER_NAME
FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
WHERE e.HIRE_DATE < m.HIRE_DATE;

SELECT JOB_ID, AVG(SALARY) AS AVG_SAL
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) > 10000;

SELECT d.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM DEPARTMENTS d
LEFT JOIN EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
WHERE e.EMPLOYEE_ID IS NULL;

SELECT FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT = (SELECT MAX(COMMISSION_PCT) FROM EMPLOYEES);
