INSERT INTO DOCTORS (DOCTOR_NAME, SPECIALIZATION) VALUES ('Dr. Ali', 'Cardiology');
INSERT INTO APPOINTMENTS (DOCTOR_ID, PATIENT_ID, APPOINTMENT_DATE, STATUS)
VALUES (
    (SELECT DOCTOR_ID FROM DOCTORS WHERE DOCTOR_NAME = 'Dr. Ali'),
    (SELECT PATIENT_ID FROM PATIENTS WHERE PATIENT_NAME = 'Zain'),
    TO_DATE('2023-08-01', 'YYYY-MM-DD'),
    'Scheduled'
);

INSERT INTO PRESCRIPTIONS (APPOINTMENT_ID, MEDICINE_NAME, DOSAGE, DURATION)
VALUES (
    (SELECT APPOINTMENT_ID FROM APPOINTMENTS 
     WHERE DOCTOR_ID = (SELECT DOCTOR_ID FROM DOCTORS WHERE DOCTOR_NAME = 'Dr. Ali')
     AND PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE PATIENT_NAME = 'Zain')),
    'Amoxicillin', '500mg', '7 days'
);

UPDATE APPOINTMENTS
SET STATUS = 'Completed'
WHERE DOCTOR_ID = (SELECT DOCTOR_ID FROM DOCTORS WHERE DOCTOR_NAME = 'Dr. Ali')
AND PATIENT_ID = (SELECT PATIENT_ID FROM PATIENTS WHERE PATIENT_NAME = 'Zain');

SELECT DISTINCT p.PATIENT_NAME
FROM PATIENTS p
JOIN APPOINTMENTS a ON p.PATIENT_ID = a.PATIENT_ID
JOIN DOCTORS d ON a.DOCTOR_ID = d.DOCTOR_ID
WHERE d.SPECIALIZATION = 'Cardiology';

SELECT d.DOCTOR_NAME, p.PATIENT_NAME, a.APPOINTMENT_DATE, a.STATUS, pr.MEDICINE_NAME
FROM APPOINTMENTS a
JOIN DOCTORS d ON a.DOCTOR_ID = d.DOCTOR_ID
JOIN PATIENTS p ON a.PATIENT_ID = p.PATIENT_ID
JOIN PRESCRIPTIONS pr ON pr.APPOINTMENT_ID = a.APPOINTMENT_ID;

SELECT MEDICINE_NAME, COUNT(*) AS TIMES_PRESCRIBED
FROM PRESCRIPTIONS
GROUP BY MEDICINE_NAME
ORDER BY TIMES_PRESCRIBED DESC
FETCH FIRST 1 ROWS ONLY;

