SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;

SELECT d.DEPARTMENT_NAME FROM DEPARTMENTS d JOIN EMPLOYEES e ON d.DEPARTMENT_ID=e.DEPARTMENT_ID GROUP BY d.DEPARTMENT_NAME HAVING COUNT(e.EMPLOYEE_ID)>5;
SELECT e.FIRST_NAME||e.LAST_NAME AS EMP_NAME,e.SALARY,d.DEPARTMENT_NAME,((SELECT AVG(e1.SALARY) FROM EMPLOYEES e1 WHERE e1.DEPARTMENT_ID = e.DEPARTMENT_ID)) AS AVG_SALARY FROM EMPLOYEES e JOIN DEPARTMENTS d ON e.DEPARTMENT_ID=d.DEPARTMENT_ID WHERE e.SALARY > (SELECT AVG(e2.SALARY) FROM EMPLOYEES e2 WHERE e2.DEPARTMENT_ID = e.DEPARTMENT_ID);
SELECT * FROM (SELECT FIRST_NAME AS EMP_NAME,SALARY,JOB_ID FROM EMPLOYEES order by (salary) DESC) WHERE ROWNUM<=5;
SELECT e.* FROM EMPLOYEES e WHERE (e.JOB_ID=(SELECT JOB_ID FROM EMPLOYEES WHERE FIRST_NAME='Peter' AND LAST_NAME='Tucker') ) AND FIRST_NAME!='Peter' AND LAST_NAME!='Tucker';
SELECT COUNTRY_NAME FROM (SELECT c.COUNTRY_NAME FROM COUNTRIES c JOIN LOCATIONS l ON c.COUNTRY_ID=l.COUNTRY_ID JOIN DEPARTMENTS d ON d.LOCATION_ID=l.LOCATION_ID JOIN EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID GROUP BY c.COUNTRY_NAME
ORDER BY (COUNT(e.EMPLOYEE_ID))DESC)WHERE ROWNUM =1;
SELECT JOB_ID FROM EMPLOYEES GROUP BY JOB_ID HAVING AVG(SALARY)> (SELECT AVG(SALARY) FROM EMPLOYEES);
SELECT e.FIRST_NAME||e.LAST_NAME AS EMP_NAME FROM EMPLOYEES e JOIN DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID WHERE e.SALARY > ANY (SELECT
e1.SALARY FROM EMPLOYEES e1 JOIN DEPARTMENTS d1 ON e1.DEPARTMENT_ID=d1.DEPARTMENT_ID WHERE d1.DEPARTMENT_NAME='SALES');
SELECT d.DEPARTMENT_NAME FROM DEPARTMENTS d LEFT JOIN EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID WHERE e.EMPLOYEE_ID IS NULL;
SELECT e.FIRST_NAME||e.LAST_NAME AS EMP_NAME, e.HIRE_DATE, m.FIRST_NAME AS MANAGER_NAME, m.HIRE_DATE AS MANAGER_HIRE_DATE FROM EMPLOYEES e LEFT JOIN EMPLOYEES m ON m.EMPLOYEE_ID=e.MANAGER_ID;
SELECT e.FIRST_NAME||e.LAST_NAME AS EMP_NAME FROM EMPLOYEES e WHERE e.SALARY < (
    SELECT AVG(e2.SALARY)
    FROM EMPLOYEES e2
    WHERE e2.DEPARTMENT_ID = e.DEPARTMENT_ID
) AND e.SALARY > (
SELECT AVG(e3.SALARY )FROM EMPLOYEES e3 WHERE e3.JOB_ID=e.JOB_ID);
